// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-G2fYGxlimN8b9tcCIj4ht1vSyZHdzE',
    appId: '1:46345706800:web:be15230e30cbd971007cf5',
    messagingSenderId: '46345706800',
    projectId: 'leyvacarsmovil',
    authDomain: 'leyvacarsmovil.firebaseapp.com',
    storageBucket: 'leyvacarsmovil.firebasestorage.app',
    measurementId: 'G-E9DPLGEFHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOkwNYd3Ne0ji_CtD-SEpX-j4uURqkpE',
    appId: '1:46345706800:android:84b6d8033f175a89007cf5',
    messagingSenderId: '46345706800',
    projectId: 'leyvacarsmovil',
    storageBucket: 'leyvacarsmovil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqos7EgtQ3NPhE_2Yy82Mygt5aDW4n9BM',
    appId: '1:46345706800:ios:41092415790d59dd007cf5',
    messagingSenderId: '46345706800',
    projectId: 'leyvacarsmovil',
    storageBucket: 'leyvacarsmovil.firebasestorage.app',
    iosBundleId: 'com.example.leyvacarsmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqos7EgtQ3NPhE_2Yy82Mygt5aDW4n9BM',
    appId: '1:46345706800:ios:41092415790d59dd007cf5',
    messagingSenderId: '46345706800',
    projectId: 'leyvacarsmovil',
    storageBucket: 'leyvacarsmovil.firebasestorage.app',
    iosBundleId: 'com.example.leyvacarsmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-G2fYGxlimN8b9tcCIj4ht1vSyZHdzE',
    appId: '1:46345706800:web:60c92ceed582427f007cf5',
    messagingSenderId: '46345706800',
    projectId: 'leyvacarsmovil',
    authDomain: 'leyvacarsmovil.firebaseapp.com',
    storageBucket: 'leyvacarsmovil.firebasestorage.app',
    measurementId: 'G-ETYG1TMR7W',
  );
}
